# Generated by Django 4.2.3 on 2023-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
                ('descripcion_curso', models.CharField(max_length=250)),
                ('fecha_inicio_curso', models.TimeField()),
                ('fecha_fin_curso', models.TimeField()),
                ('fecha_creacion_cursso', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
