# Generated by Django 4.2.3 on 2023-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fecha_creacion_cursso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_fin_curso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_inicio_curso',
            field=models.DateTimeField(),
        ),
    ]
