# Generated by Django 4.2.3 on 2023-07-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_cursos_fecha_creacion_cursso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='fecha_creacion_cursso',
            new_name='fecha_creacion_curso',
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=50)),
                ('descripcion_tarea', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to=None)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.cursos')),
            ],
        ),
    ]
