# Generated by Django 4.2.3 on 2023-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_cursos_curso_rename_tareas_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
