# Generated by Django 4.2.3 on 2023-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_tarea_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo_pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
