# Generated by Django 4.2.3 on 2023-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_tarea_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='archivo_pdf',
            field=models.FileField(default=True, upload_to='imgs/'),
        ),
    ]
