# Generated by Django 4.2.3 on 2023-07-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_curso_archivo_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='archivo_pdf',
            new_name='img_curso',
        ),
    ]
