# Generated by Django 4.2.3 on 2023-07-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo_pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
