# Generated by Django 4.2.3 on 2023-07-31 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0010_alter_tarea_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo_pdf',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.CreateModel(
            name='Tarea_hecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], max_length=100, null=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.tarea')),
            ],
        ),
    ]
