# Generated by Django 4.2.3 on 2023-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_userrole_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_hecha',
            name='tarea',
            field=models.FileField(blank=True, upload_to='', verbose_name='pdfs/alumno/'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='alumno', max_length=100),
        ),
    ]
