# Generated by Django 4.2.3 on 2023-08-02 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_tarea_hecha_tarea_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='puntos',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
