# Generated by Django 4.2.3 on 2023-08-02 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_tarea_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_hecha',
            name='puntos_hechos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
