# Generated by Django 4.2.3 on 2023-08-02 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_alter_tarea_hecha_puntos_hechos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_hecha',
            name='puntos_hechos',
            field=models.IntegerField(blank=True, default='No corregido', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
