# Generated by Django 4.2.3 on 2023-08-03 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0019_alter_tarea_hecha_puntos_hechos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_hecha',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Corregido', 'Corregido')], default=('Pendiente', 'Pendiente'), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea_hecha',
            name='puntos_hechos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('id_alumno', 'id_curso')},
        ),
    ]
