# Generated by Django 4.2.3 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_remove_tarea_docente_curso_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion_curso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion_tarea',
            field=models.TextField(max_length=250),
        ),
    ]
